pull_request_rules:
  - name: automatically approve dependabot pull requests
    conditions:
      - author~=dependabot\[bot\]|dependabot-preview\[bot\]
      - status-success=continuous-integration/appveyor/branch
      - status-success=continuous-integration/appveyor/pr
      - status-success=continuous-integration/travis-ci/pr
      - status-success=continuous-integration/travis-ci/push
    actions:
      review:
        type: APPROVE

  - name: automatically merge dependabot pull requests
    conditions:
      - author~=dependabot\[bot\]|dependabot-preview\[bot\]
      - "#approved-reviews-by>=1"
    actions:
      merge:
        method: merge

  - name: automatically approve GitHub Action pull requests
    conditions:
      - author~=github-actions\[bot\]
      - status-success=continuous-integration/appveyor/pr
      - status-success=continuous-integration/travis-ci/pr
    actions:
      review:
        type: APPROVE

  - name: automatically merge GitHub Action pull requests
    conditions:
      - author~=github-actions\[bot\]
      - "#approved-reviews-by>=1"
    actions:
      merge:
        method: merge
