version: '{branch}-{build}'
build: "off"
image: Visual Studio 2015
cache:
  - '%LOCALAPPDATA%\pip\Cache'
install:
  - pip install pipenv
  - pipenv --python 3
  - pipenv install -r requirements/pip.txt
  - pipenv install -r requirements/test.txt 
  - pipenv install -e .

test_script:
  - pipenv run pytest
